Style/StringLiterals:
  EnforcedStyle: double_quotes


AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*.rb'
